// Package sdkgen generates a self-contained, typed TypeScript SDK from the
// live collection schema. It runs at the application layer (no PostgREST) and
// produces a single importable module containing one interface per collection
// plus a typed client that wraps fetch with per-collection CRUD methods.
package sdkgen

import (
	"fmt"
	"strings"

	"github.com/gresbase/gresbase/internal/collection"
)

// Generate returns a self-contained TypeScript module for the given
// collections. baseURL is embedded as the default API base for the generated
// client. System collections (names starting with "_") are skipped. The empty
// collection list is handled gracefully — a valid module with no record
// interfaces is still emitted.
func Generate(collections []*collection.Collection, baseURL string) string {
	var b strings.Builder

	writeHeader(&b, baseURL)

	// Only user-facing collections get interfaces and client methods.
	visible := make([]*collection.Collection, 0, len(collections))
	for _, coll := range collections {
		if coll == nil || strings.HasPrefix(coll.Name, "_") {
			continue
		}
		visible = append(visible, coll)
	}

	for _, coll := range visible {
		writeInterface(&b, coll)
	}

	writeClient(&b, visible, baseURL)

	return b.String()
}

// writeHeader emits the module banner and shared option types.
func writeHeader(b *strings.Builder, baseURL string) {
	b.WriteString("// Code generated by gresbase sdkgen. DO NOT EDIT.\n")
	b.WriteString("// Typed TypeScript SDK generated from the live collection schema.\n")
	if baseURL != "" {
		fmt.Fprintf(b, "// Base URL: %s\n", baseURL)
	}
	b.WriteString("\n")
	b.WriteString("export interface ListOptions {\n")
	b.WriteString("  page?: number;\n")
	b.WriteString("  perPage?: number;\n")
	b.WriteString("  filter?: string;\n")
	b.WriteString("  sort?: string;\n")
	b.WriteString("  expand?: string;\n")
	b.WriteString("}\n\n")
	b.WriteString("export interface ListResult<T> {\n")
	b.WriteString("  items: T[];\n")
	b.WriteString("  page: number;\n")
	b.WriteString("  perPage: number;\n")
	b.WriteString("  totalItems: number;\n")
	b.WriteString("  totalPages: number;\n")
	b.WriteString("}\n\n")
}

// writeInterface emits one exported interface for a collection.
func writeInterface(b *strings.Builder, coll *collection.Collection) {
	name := interfaceName(coll.Name)
	fmt.Fprintf(b, "export interface %s {\n", name)
	b.WriteString("  id: string;\n")

	for _, field := range coll.Schema {
		if field.Name == "id" || field.Name == "created_at" || field.Name == "updated_at" {
			continue
		}
		optional := ""
		if !field.Required {
			optional = "?"
		}
		fmt.Fprintf(b, "  %s%s: %s;\n", field.Name, optional, tsType(field))
	}

	if coll.Type == collection.TypeAuth {
		b.WriteString("  email?: string;\n")
		b.WriteString("  verified?: boolean;\n")
	}

	b.WriteString("  created_at: string;\n")
	b.WriteString("  updated_at: string;\n")
	b.WriteString("}\n\n")
}

// tsType maps a schema field to its TypeScript type representation.
func tsType(field collection.SchemaField) string {
	switch field.Type {
	case collection.FieldText, collection.FieldEmail, collection.FieldURL,
		collection.FieldEditor, collection.FieldPassword:
		return "string"
	case collection.FieldNumber:
		return "number"
	case collection.FieldBool:
		return "boolean"
	case collection.FieldDate, collection.FieldAutoDate:
		return "string"
	case collection.FieldJSON:
		return "any"
	case collection.FieldFile:
		return "string | string[]"
	case collection.FieldRelation:
		return "string | string[]"
	case collection.FieldSelect:
		return selectUnion(field)
	case collection.FieldGeoPoint:
		return "{ lat: number; lng: number }"
	case collection.FieldVector:
		return "number[]"
	default:
		return "any"
	}
}

// selectUnion builds a string-literal union from a select field's options when
// values are present, otherwise falls back to plain string.
func selectUnion(field collection.SchemaField) string {
	values := selectValues(field.Options)
	if len(values) == 0 {
		return "string"
	}
	parts := make([]string, 0, len(values))
	for _, v := range values {
		parts = append(parts, tsStringLiteral(v))
	}
	return strings.Join(parts, " | ")
}

// selectValues extracts the option values from a select field's options map,
// tolerating the various concrete types JSON decoding may produce.
func selectValues(opts map[string]any) []string {
	if opts == nil {
		return nil
	}
	raw, ok := opts["values"]
	if !ok {
		return nil
	}
	var out []string
	switch vs := raw.(type) {
	case []string:
		out = append(out, vs...)
	case []any:
		for _, v := range vs {
			if s, ok := v.(string); ok {
				out = append(out, s)
			} else {
				out = append(out, fmt.Sprint(v))
			}
		}
	}
	return out
}

// writeClient emits the typed GresbaseTyped client class.
func writeClient(b *strings.Builder, collections []*collection.Collection, baseURL string) {
	b.WriteString("export class GresbaseTyped {\n")
	b.WriteString("  private baseURL: string;\n")
	b.WriteString("  private token?: string;\n\n")
	fmt.Fprintf(b, "  constructor(baseURL: string = %s, token?: string) {\n", tsStringLiteral(baseURL))
	b.WriteString("    this.baseURL = baseURL.replace(/\\/$/, \"\");\n")
	b.WriteString("    this.token = token;\n")
	b.WriteString("  }\n\n")

	b.WriteString("  setToken(token?: string): void {\n")
	b.WriteString("    this.token = token;\n")
	b.WriteString("  }\n\n")

	// Internal request helper.
	b.WriteString("  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {\n")
	b.WriteString("    const headers: Record<string, string> = { \"Content-Type\": \"application/json\" };\n")
	b.WriteString("    if (this.token) headers[\"Authorization\"] = `Bearer ${this.token}`;\n")
	b.WriteString("    const res = await fetch(`${this.baseURL}${path}`, {\n")
	b.WriteString("      method,\n")
	b.WriteString("      headers,\n")
	b.WriteString("      body: body !== undefined ? JSON.stringify(body) : undefined,\n")
	b.WriteString("    });\n")
	b.WriteString("    if (!res.ok) {\n")
	b.WriteString("      const text = await res.text();\n")
	b.WriteString("      throw new Error(`Gresbase request failed (${res.status}): ${text}`);\n")
	b.WriteString("    }\n")
	b.WriteString("    if (res.status === 204) return undefined as T;\n")
	b.WriteString("    return (await res.json()) as T;\n")
	b.WriteString("  }\n\n")

	// Query string builder for list options.
	b.WriteString("  private query(opts?: ListOptions): string {\n")
	b.WriteString("    if (!opts) return \"\";\n")
	b.WriteString("    const params = new URLSearchParams();\n")
	b.WriteString("    if (opts.page !== undefined) params.set(\"page\", String(opts.page));\n")
	b.WriteString("    if (opts.perPage !== undefined) params.set(\"perPage\", String(opts.perPage));\n")
	b.WriteString("    if (opts.filter !== undefined) params.set(\"filter\", opts.filter);\n")
	b.WriteString("    if (opts.sort !== undefined) params.set(\"sort\", opts.sort);\n")
	b.WriteString("    if (opts.expand !== undefined) params.set(\"expand\", opts.expand);\n")
	b.WriteString("    const s = params.toString();\n")
	b.WriteString("    return s ? `?${s}` : \"\";\n")
	b.WriteString("  }\n")

	for _, coll := range collections {
		writeCollectionAccessor(b, coll)
	}

	b.WriteString("}\n")
}

// writeCollectionAccessor emits a getter returning per-collection CRUD methods.
func writeCollectionAccessor(b *strings.Builder, coll *collection.Collection) {
	iface := interfaceName(coll.Name)
	prop := methodName(coll.Name)
	encoded := encodeURIPath(coll.Name)

	b.WriteString("\n")
	fmt.Fprintf(b, "  get %s() {\n", prop)
	b.WriteString("    const self = this;\n")
	fmt.Fprintf(b, "    const base = `/records/%s`;\n", encoded)
	b.WriteString("    return {\n")
	fmt.Fprintf(b, "      list(opts?: ListOptions): Promise<ListResult<%s>> {\n", iface)
	fmt.Fprintf(b, "        return self.request<ListResult<%s>>(\"GET\", `${base}${self.query(opts)}`);\n", iface)
	b.WriteString("      },\n")
	fmt.Fprintf(b, "      getOne(id: string, opts?: Pick<ListOptions, \"expand\">): Promise<%s> {\n", iface)
	fmt.Fprintf(b, "        return self.request<%s>(\"GET\", `${base}/${encodeURIComponent(id)}${self.query(opts)}`);\n", iface)
	b.WriteString("      },\n")
	fmt.Fprintf(b, "      create(data: Partial<%s>): Promise<%s> {\n", iface, iface)
	fmt.Fprintf(b, "        return self.request<%s>(\"POST\", base, data);\n", iface)
	b.WriteString("      },\n")
	fmt.Fprintf(b, "      update(id: string, data: Partial<%s>): Promise<%s> {\n", iface, iface)
	fmt.Fprintf(b, "        return self.request<%s>(\"PATCH\", `${base}/${encodeURIComponent(id)}`, data);\n", iface)
	b.WriteString("      },\n")
	b.WriteString("      delete(id: string): Promise<void> {\n")
	b.WriteString("        return self.request<void>(\"DELETE\", `${base}/${encodeURIComponent(id)}`);\n")
	b.WriteString("      },\n")
	b.WriteString("    };\n")
	b.WriteString("  }\n")
}

// ---------------------------------------------------------------------------
// Naming + escaping helpers
// ---------------------------------------------------------------------------

// interfaceName converts a collection name into a PascalCase TypeScript
// interface identifier (e.g. "blog_posts" -> "BlogPosts").
func interfaceName(name string) string {
	parts := splitName(name)
	if len(parts) == 0 {
		return "Record_"
	}
	var b strings.Builder
	for _, p := range parts {
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	out := sanitizeIdent(b.String())
	if out == "" {
		return "Record_"
	}
	return out
}

// methodName converts a collection name into a camelCase property identifier
// used on the client (e.g. "blog_posts" -> "blogPosts").
func methodName(name string) string {
	parts := splitName(name)
	if len(parts) == 0 {
		return "collection_"
	}
	var b strings.Builder
	for i, p := range parts {
		if i == 0 {
			b.WriteString(strings.ToLower(p[:1]) + p[1:])
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	out := sanitizeIdent(b.String())
	if out == "" {
		return "collection_"
	}
	// A leading digit is not a valid identifier start.
	if out[0] >= '0' && out[0] <= '9' {
		return "_" + out
	}
	return out
}

// splitName breaks a collection name on common word separators.
func splitName(name string) []string {
	fields := strings.FieldsFunc(name, func(r rune) bool {
		return r == '_' || r == '-' || r == ' ' || r == '.'
	})
	out := make([]string, 0, len(fields))
	for _, f := range fields {
		if f != "" {
			out = append(out, f)
		}
	}
	return out
}

// sanitizeIdent strips characters that are invalid in a TS identifier.
func sanitizeIdent(s string) string {
	var b strings.Builder
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// encodeURIPath escapes a collection name for safe interpolation into a URL
// path segment within a backtick template literal.
func encodeURIPath(name string) string {
	var b strings.Builder
	for _, r := range name {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') ||
			r == '-' || r == '_' || r == '.' || r == '~' {
			b.WriteRune(r)
			continue
		}
		for _, by := range []byte(string(r)) {
			fmt.Fprintf(&b, "%%%02X", by)
		}
	}
	return b.String()
}

// tsStringLiteral renders a Go string as a double-quoted TypeScript literal.
func tsStringLiteral(s string) string {
	r := strings.NewReplacer(
		"\\", "\\\\",
		"\"", "\\\"",
		"\n", "\\n",
		"\r", "\\r",
		"\t", "\\t",
	)
	return "\"" + r.Replace(s) + "\""
}
